const express = require("express")
const router = express.Router()
const reportController = require("../controllers/reportController")
router.post("/report",reportController.createReport)
router.delete("/report",reportController.deleteReport)
router.get("/report",reportController.readAllReport)
router.get("/report/:id",reportController.readReportById)
router.get("/report/student/:sid",reportController.readReportBySid)
router.put("/report/:id",reportController.updateReport)
module.exports=router